num1,num2=input().split(" ")
print("%d+%d=%d" %(int(num1),int(num2),int(num1)+int(num2)))
print("%d-%d=%d" %(int(num1),int(num2),int(num1)-int(num2)))
print("%d*%d=%d" %(int(num1),int(num2),int(num1)*int(num2)))
print("%d/%d=%d" %(int(num1),int(num2),int(num1)/int(num2)))